version: "3.5"
services:
  database:
    image: mysql:latest
    container_name: database
    ports:
      - 3306:3306
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./config.cnf:/etc/mysql/conf.d/config.cnf
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
volumes:
  db_data:
